### PR TITLE
fix: avoid accessing undeclared instance fields on type level

### LINKED ISSUE #187: Instance type of VueProxy allows any field access when props is not specified
version: 0.3.2

### Reproduction

https://codesandbox.io/s/vuecomposition-api-type-issue-dc492

### Expected Behavior

`comp.foo` should be error as there are no field type `foo` in the component.

### Actual Behavior

No error is provided.

---

This behavior would be a problem if the users enable [template type checking which Vetur offers](https://vuejs.github.io/vetur/interpolation.html).
As Vetur uses component instance type to check expression, it cannot provide diagnostic message even if an accessed field is defined on the component.

### PR DESCRIPTION
**Pull request by ktsn**
fix #187 

As `never` is bottom type, `ExtractPropTypes<never>` is resolved as a type that accepts any field access:

```
ExtractPropTypes<never> = {
    readonly [x: string]: undefined;
    readonly [x: number]: undefined;
}
```

which is included in intersections of `ComponentRenderProxy` type, consists of `VueProxy` instance type.

The default type of `Props` seems to be `unknown`. As it is top type, `ExtractPropTypes<unknown>` will be `{}` which is expected type in this case.

### CODE REVIEW

File: src/component/component.ts [hunk 1]
```diff
@@ -22,8 +22,8 @@ export type ComponentRenderProxy<P = {}, S = {}, PublicProps = P> = {
   S;
 
 // for Vetur and TSX support
-type VueConstructorProxy<PropsOptions, RawBindings> = {
-  new (): ComponentRenderProxy<
+type VueConstructorProxy<PropsOptions, RawBindings> = VueConstructor & {
+  new (...args: any[]): ComponentRenderProxy<
```
Comment (ktsn) [inline src/component/component.ts]: Modified this type as it cannot match existing typings which expects `VueConstructor` like vue-router. By writing argument as `(...args: any[])`, we can mix it with the intersected constructor so that `ComponentRenderProxy` retains even after inherit `VueConstructor`.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html

This probably fixes #185 ?

**Comment by ux-engineer** [comment]
Does this get merged?

**Comment by dodas** [comment]
This solves #185 for me!

**Comment by yoyo930021** [comment]
This PR can fix #185.
