### PR TITLE
fix: better `vueDependency` importing, close #564

### LINKED ISSUE #564: error Cannot read property 'silent' of undefined
I'm having a problem with it.

My project is in esm mode, so I use @vue/compostition-api esm version of the code.

I define the following code.

```js
import {ref} from '@vue/compostition-api';
const a = ref(false);

export  function useA () {
   return {a};
}; 
```
```js
...
setup(){
  const {a} = useA()
}
```
I got an error.
image
image

When I debugger.
https://github.com/vuejs/composition-api/blob/3a1d99263c91db45fdf90cbd6bb1da9ed2ff20f1/src/runtimeContext.ts#L8
https://github.com/vuejs/composition-api/blob/3a1d99263c91db45fdf90cbd6bb1da9ed2ff20f1/src/runtimeContext.ts#L39
`vueConstructor` is null 
`vueDependency` is {default: ...}

Whether `vueDependency`  should be dealt with. or use `import`, let babel or webpack handle it.

Or there is a problem with my project configuration.  
How it needs to be configured.

### PR DESCRIPTION
**Pull request by antfu**
close #564

### CODE REVIEW

File: src/runtimeContext.ts [hunk 1]
```diff
@@ -5,7 +5,16 @@ import { assert, hasOwn, warn } from './utils'
...
-  vueDependency = require('vue')
+  const requiredVue = require('vue')
+  if (requiredVue && isVue(requiredVue)) {
+    vueDependency = requiredVue
+  } else if (
+    requiredVue &&
+    'deafult' in requiredVue &&
+    isVue(requiredVue.deafult)
+  ) {
+    vueDependency = requiredVue.deafult
```
Comment (kiroushi) [inline src/runtimeContext.ts:16]:
```suggestion
    'default' in requiredVue &&
    isVue(requiredVue.default)
  ) {
    vueDependency = requiredVue.default
```

Guess this is a typo.

Comment (antfu) [reply src/runtimeContext.ts]: I must be too sleepy 😓

**Review by pikax — APPROVED** [review]
