### PR TITLE
fix(types): prop type infer, fix #555

### LINKED ISSUE #555: Bug: PropType not working on some types
Vue3:

image

---

composition-api:

image

Could this be fixed?

### PR DESCRIPTION
**Pull request by Mister-Hope**
Improve prop type infering

Fix #555

### CODE REVIEW

File: src/component/componentProps.ts [hunk 1]
```diff
@@ -49,24 +42,23 @@ type ExtractCorrectPropType<T> = T extends Function
...
+  ? Record<string, any>
+  : T extends BooleanConstructor | { type: BooleanConstructor }
+  ? boolean
+  : T extends FunctionConstructor
+  ? Function
+  : T extends Prop<infer V, infer D>
+  ? unknown extends V
+    ? D
+    : ExtractCorrectPropType<V>
+  : T
```
Comment (antfu) [inline src/component/componentProps.ts:59]: Could you keep the format as https://github.com/vuejs/vue-next/blob/c6443a43c9744d8d40f7129a98792debe07a3a82/packages/runtime-core/src/componentProps.ts#L77-L85

**Review by antfu — APPROVED** [review]
