### PR TITLE
fix(unwrapRef): copy __ob__ and make toRaw work in props

### LINKED ISSUE #392: toRaw does not undo props auto unwrapping
composition-api v0.6.5 toRaw does not unwrap reactive:

```js
toRaw(reactive({ "ref": ref(1) }))
```

In vue-next same code works as expected.

### PR DESCRIPTION
**Pull request by antfu**
fix #392

### CODE REVIEW

File: src/reactivity/unwrap.ts [hunk 1]
```diff
@@ -27,6 +27,11 @@ export function unwrapRefProxy(value: any, map = new WeakMap()) {
     (s) => (obj[s] = (value as any)[s])
   )
 
+  // copy __ob__
+  if (value.__ob__) {
```
Comment (pikax) [inline src/reactivity/unwrap.ts:31]: shouldn't that be part of the `Object.keys`? if so can we just add it there when the key is `__ob__`?

Comment (antfu) [reply src/reactivity/unwrap.ts:31]: [It's defined by `defineProperty`](https://github.com/vuejs/vue/blob/0b31647c41b0c916d40b962723b1de06672d0e01/src/core/observer/index.js#L46) which is not enumerable by `Object.keys`
